"""game-session gamemode changes

Revision ID: dce783834f69
Revises: 65ffe7142416
Create Date: 2025-07-16 19:34:09.822735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce783834f69'
down_revision: Union[str, None] = '65ffe7142416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('game_mode', sa.Enum('SOLO', 'TEAM', name='gamemode'), nullable=False))
    op.add_column('game_sessions', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('leaderboard', sa.Column('rank', sa.Integer(), nullable=True))

    # SQLite workaround for altering column type
    with op.batch_alter_table('leaderboard') as batch_op:
        batch_op.drop_column('total_score')
    op.add_column('leaderboard', sa.Column('total_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'rank')
    op.drop_column('game_sessions', 'timestamp')
    op.drop_column('game_sessions', 'game_mode')

    # SQLite workaround for altering column type
    with op.batch_alter_table('leaderboard') as batch_op:
        batch_op.drop_column('total_score')
    op.add_column('leaderboard', sa.Column('total_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
